// packages/qwik/src/ColourPicker.tsx
/** An OKLCH colour picker: one slider per axis, each over a gamut cross-section. */
import { $, type QRL, component$, useComputed$, useId, useStore } from "@builder.io/qwik";
import type { Axis, LabelKey, Oklch, PickerLayout, PickerParts } from "@oklch-picker/core";
import {
  addRecent,
  chartPick,
  colourName,
  emitValue,
  pickerModel,
  recentValue,
  resolveCurrent,
  toOklch,
  withSingleChart,
} from "@oklch-picker/core";
import { GamutChart } from "./GamutChart.js";
import { type GamutId, gamutFrom, gamutsFrom, idOf } from "./gamuts.js";

export interface ColourPickerProps {
  /** `oklch(L C H)` or hex. */
  value?: string | null | undefined;
  /** A canonical, gamut-clamped `oklch(L C H)` string. */
  onChange$?: QRL<(colour: string) => void>;
  presets?: string[] | undefined;
  /** Recently used colours, most recent first. Omit to let the picker keep its
   * own list for the session; pass one to store them yourself. */
  recents?: string[] | undefined;
  /** The new list when a colour is committed. Fires on commit, so on a pointer
   * release, a preset, or a text entry. Not on every value a drag passes
   * through. */
  onRecentsChange$?: QRL<(recents: string[]) => void>;
  /** How many recents to keep. Ignored when `recents` is controlled. */
  maxRecents?: number | undefined;
  /** Visual arrangement. `chart` (the default) shows one large
   * lightness x chroma plot above all three sliders. */
  layout?: PickerLayout | undefined;
  /** Turn parts off, e.g. `{ charts: false, name: false }`. All on by default. */
  parts?: PickerParts | undefined;
  /** Override for translation. */
  labels?: Partial<Record<LabelKey, string>> | undefined;
  /** The output space, by id: what the sliders reach, what is clamped, and what
   * is emitted. An id rather than a `Gamut` object, because Qwik serialises
   * props and a `Gamut` carries a function. See `gamuts.ts`. */
  gamut?: GamutId | undefined;
  /** Spaces to outline on the charts without clamping to them. */
  references?: GamutId[] | undefined;
  /** What the switcher offers, when `parts.gamutSwitch` is on. */
  gamutChoices?: GamutId[] | undefined;
  /** A switcher button was pressed, carrying the new gamut's id. */
  onGamutChange$?: QRL<(gamut: GamutId) => void>;
  /** Class prefix for every element, so styles can be overridden. */
  classPrefix?: string | undefined;
  class?: string | undefined;
}

export const ColourPicker = component$<ColourPickerProps>((props) => {
  const prefix = props.classPrefix ?? "oklch-picker";
  // `useId` rather than a module counter. The optimizer splits each `$()` into
  // its own chunk, and a counter there becomes an imported binding that cannot
  // be incremented: "Illegal reassignment of import". Only a production build
  // surfaces that, so the example app is what caught it. `useId` is also stable
  // across the server render and the resumption that follows.
  const uid = useId();

  /** What was dialled, not what was emitted: dragging through an out-of-gamut
   * region must not destroy the other axes.
   *
   * A store rather than a signal, because Qwik serialises the draft to resume
   * the component and a plain object round-trips where a class would not. */
  const draft = useStore<{ current: Oklch | null }>({ current: null });

  /** Recents are uncontrolled until `recents` is passed, mirroring how `value`
   * works. The internal list is kept regardless so switching to controlled
   * mid-session does not lose it. */
  const ownRecents = useStore<{ list: string[] }>({ list: [] });

  const recents = useComputed$(() => props.recents ?? ownRecents.list);

  /** The output space decides what `resolveCurrent` compares against, so it is
   * read from the prop here rather than from the model it feeds. */
  const current = useComputed$(() =>
    resolveCurrent(draft.current, props.value, gamutFrom(props.gamut)),
  );

  /** The scale gamuts as ids, computed rather than mapped inline.
   *
   * Mapping in the JSX builds a new array on every render. Qwik sees a changed
   * prop each time, and the re-render that follows drops the whole component's
   * event bindings: the first slider move works and every one after it is
   * silently ignored. A computed keeps the reference stable.
   *
   * Ids rather than the gamuts themselves, for the same serialisation reason
   * as the props. */
  /** The references the model derived, as ids. sRGB is outlined whenever the
   * output space is wider, so passing the raw prop through drew nothing. */
  const referenceIds = useComputed$(() =>
    pickerModel(current.value, {
      layout: props.layout,
      parts: props.parts,
      gamut: gamutFrom(props.gamut),
      references: gamutsFrom(props.references),
      gamutChoices: gamutsFrom(props.gamutChoices),
    }).references.map(idOf),
  );

  const scaleIds = useComputed$(() =>
    pickerModel(current.value, {
      layout: props.layout,
      parts: props.parts,
      gamut: gamutFrom(props.gamut),
      references: gamutsFrom(props.references),
      gamutChoices: gamutsFrom(props.gamutChoices),
    }).scaleGamuts.map(idOf),
  );

  const emit = $(async (next: Oklch) => {
    draft.current = next;
    await props.onChange$?.(emitValue(next, gamutFrom(props.gamut)));
  });

  /** A drag calls `onChange$` for every value it passes through, so recording
   * there would bury the list in near-identical colours from one gesture. Only
   * a commit lands here. */
  const commit = $(async (colour: string) => {
    const next = addRecent(props.recents ?? ownRecents.list, colour, props.maxRecents);
    ownRecents.list = next;
    await props.onRecentsChange$?.(next);
  });

  /** Null while the dialled colour is outside the gamut, so a drag released in
   * a hatched region records nothing rather than the clamped near-miss. */
  const commitCurrent = $(async () => {
    const colour = recentValue(current.value, gamutFrom(props.gamut));
    if (colour) await commit(colour);
  });

  const pick = $(async (colour: string) => {
    draft.current = null;
    await props.onChange$?.(colour);
    await commit(colour);
  });

  /** `toOklch` rather than a per-field parser: a field accepts any supported
   * format whichever one it shows, so pasting a hex into the oklch field works
   * instead of being a rule to learn. */
  const editColour = $(async (raw: string) => {
    const parsed = toOklch(raw);
    if (parsed) await emit(parsed);
  });

  /** Derived during render rather than held in a `useComputed$`.
   *
   * A `PickerModel` carries the resolved `gamut` and `scaleGamuts`, and those
   * carry `fromLms`. Qwik serialises what a computed signal holds, so keeping
   * the model in one fails the server render with "Only primitive and object
   * literals can be serialized". Recomputing per render is what the other
   * adapters do anyway: `pickerModel` is pure and cheap, and the expensive part
   * is the chart curve, which `GamutChart` memoises on its own. */
  const m = pickerModel(current.value, {
    layout: props.layout,
    parts: props.parts,
    labels: props.labels,
    gamut: gamutFrom(props.gamut),
    references: gamutsFrom(props.references),
    gamutChoices: gamutsFrom(props.gamutChoices),
  });
  /** `chart` renders one plot for the whole picker rather than one per axis. */
  const single = withSingleChart(m.layout) ? m.charts[0] : undefined;
  // Pulled out as a plain string so the pick handler captures that rather than
  // the whole slot object.
  const axis = single?.axis ?? "l";

  return (
    <div class={[prefix, `${prefix}--${m.layout}`, props.class].filter(Boolean).join(" ")}>
      {props.presets && props.presets.length > 0 && (
        <div class={`${prefix}__presets`}>
          {props.presets.map((p) => (
            <button
              key={p}
              type="button"
              class={
                p === m.canonical
                  ? `${prefix}__preset ${prefix}__preset--selected`
                  : `${prefix}__preset`
              }
              style={{ background: p }}
              aria-label={colourName(p)}
              aria-pressed={p === m.canonical}
              onClick$={() => pick(p)}
            />
          ))}
        </div>
      )}

      {m.parts.recents && recents.value.length > 0 && (
        <div class={`${prefix}__recents`}>
          {recents.value.map((r) => (
            <button
              key={r}
              type="button"
              class={
                r === m.canonical
                  ? `${prefix}__recent ${prefix}__recent--selected`
                  : `${prefix}__recent`
              }
              style={{ background: r }}
              aria-label={`Recent: ${colourName(r)}`}
              aria-pressed={r === m.canonical}
              onClick$={() => pick(r)}
            />
          ))}
        </div>
      )}

      {single && (
        <GamutChart
          base={current.value}
          axis={axis}
          id={`${uid}-${single.axis}`}
          x={single.x}
          y={single.y}
          references={referenceIds.value}
          gamut={props.gamut}
          scaleGamuts={scaleIds.value}
          classPrefix={prefix}
          onPick$={$(async (x: number, y: number) => {
            // Everything a handler needs is resolved inside it, from ids. The
            // optimizer serialises whatever a QRL closes over, so capturing
            // `m.scaleGamuts` would put `fromLms` in the serialised scope and
            // fail the server render.
            await emit(
              chartPick(
                current.value,
                axis,
                x,
                y,
                gamutFrom(props.gamut),
                scaleIds.value.map(gamutFrom),
              ),
            );
          })}
          onPicked$={commitCurrent}
        />
      )}

      <div class={`${prefix}__axes`}>
        {m.axes.map((a, i) => {
          const spans = m.spans[i] ?? [];
          // In the `chart` layout the one chart is hoisted above the axes.
          const chart = single ? undefined : m.charts[i];
          return (
            <div key={a.key} class={`${prefix}__axis`}>
              <span class={`${prefix}__axis-head`}>
                <span class={`${prefix}__axis-label`} aria-hidden="true">
                  {m.layout === "compact" ? a.key.toUpperCase() : m.labels[a.key]}
                </span>
                <output class={`${prefix}__axis-value`}>
                  {a.key === "h" ? Math.round(a.value) : a.value.toFixed(2)}
                </output>
              </span>

              {/* Read-only here: a 34px strip gives a drag almost no vertical
                  travel, and it would set two axes at once right above the
                  slider that sets one precisely. Only `chart` is big enough. */}
              {chart && (
                <GamutChart
                  base={current.value}
                  axis={a.key}
                  id={`${uid}-${a.key}`}
                  x={chart.x}
                  y={chart.y}
                  references={referenceIds.value}
                  gamut={props.gamut}
                  scaleGamuts={scaleIds.value}
                  classPrefix={prefix}
                />
              )}

              <span class={`${prefix}__track`}>
                <span class={`${prefix}__track-fill`} style={{ background: m.gradients[i] }}>
                  {spans.map((s) => (
                    <span
                      key={`${a.key}-${s.start}`}
                      class={`${prefix}__out-of-gamut`}
                      style={{ left: `${s.start * 100}%`, width: `${(s.end - s.start) * 100}%` }}
                    />
                  ))}
                </span>
                <input
                  type="range"
                  class={`${prefix}__slider`}
                  min={a.min}
                  max={a.max}
                  step={a.step}
                  value={a.value}
                  aria-label={m.labels[a.key]}
                  onInput$={(_, el) => emit({ ...current.value, [a.key]: Number(el.value) })}
                  // The gesture ending is the commit, not each value it passed
                  // through. `blur` catches the keyboard: arrowing along a
                  // slider should record once the user moves on, not per step.
                  onPointerUp$={commitCurrent}
                  onBlur$={commitCurrent}
                />
              </span>
            </div>
          );
        })}

        {/* Alpha rides with the axes for layout but is not one of them. It has
            no gamut chart and no hatching, because transparency cannot put a
            colour outside what a screen can show. */}
        {m.withAlpha && (
          <div class={`${prefix}__axis ${prefix}__alpha`}>
            <span class={`${prefix}__axis-head`}>
              <span class={`${prefix}__axis-label`} aria-hidden="true">
                {m.layout === "compact" ? "A" : "Alpha"}
              </span>
              <output class={`${prefix}__axis-value`}>{m.alpha.value.toFixed(2)}</output>
            </span>

            <span class={`${prefix}__track`}>
              <span class={`${prefix}__track-fill`}>
                <span class={`${prefix}__alpha-check`} />
                <span class={`${prefix}__alpha-ramp`} style={{ background: m.alpha.track }} />
              </span>
              <input
                type="range"
                class={`${prefix}__slider`}
                min={m.alpha.min}
                max={m.alpha.max}
                step={m.alpha.step}
                value={m.alpha.value}
                aria-label="Alpha"
                onInput$={(_, el) => {
                  // Fully opaque drops the key rather than storing `a: 1`, so a
                  // colour dragged to opaque emits `oklch(L C H)` and not
                  // `oklch(L C H / 1)`. One shape for "opaque", set in one place.
                  const a = Number(el.value);
                  const { a: _drop, ...rest } = current.value;
                  return emit(a >= 1 ? rest : { ...rest, a });
                }}
                onPointerUp$={commitCurrent}
                onBlur$={commitCurrent}
              />
            </span>
          </div>
        )}
      </div>

      {m.withGamutSwitch && (
        /* biome-ignore lint/a11y/useSemanticElements: a <fieldset> is for form
           controls and brings a legend and its own box; this is a toolbar of
           buttons, which is what role="group" describes. */
        <div class={`${prefix}__gamut-switch`} role="group" aria-label="Output gamut">
          {m.gamutChoices.map((g) => {
            // The id and label as plain strings before the handler exists. A
            // QRL serialises whatever it closes over, and `g` carries
            // `fromLms`, so capturing it drops this whole subtree silently:
            // the model says to render a switcher and no buttons appear.
            const id = idOf(g);
            const label = g.label;
            return (
              <button
                key={id}
                type="button"
                class={`${prefix}__gamut-choice`}
                aria-pressed={id === m.gamut.id}
                aria-label={`Output in ${label}`}
                onClick$={() => props.onGamutChange$?.(id)}
              >
                {label}
              </button>
            );
          })}
        </div>
      )}

      {m.withFooter && (
        <div class={`${prefix}__footer`}>
          {m.parts.preview && (
            <span
              class={`${prefix}__preview`}
              style={{ background: m.hex, color: m.light ? "#000" : "#fff" }}
              title={m.clipped ? m.notice : m.canonical}
            />
          )}
          {/* Every field accepts any supported format, whichever it displays.
              Pasting a hex into the oklch field works, because refusing it
              would be a rule the reader has to learn for no benefit. */}
          {m.parts.oklchInput && (
            <input
              class={`${prefix}__field ${prefix}__field--oklch`}
              value={m.oklch}
              spellcheck={false}
              aria-label="OKLCH colour"
              onInput$={(_, el) => editColour(el.value)}
              onBlur$={commitCurrent}
            />
          )}
          {m.parts.rgbInput && (
            <input
              class={`${prefix}__field ${prefix}__field--rgb`}
              value={m.rgb}
              spellcheck={false}
              aria-label="RGB colour"
              onInput$={(_, el) => editColour(el.value)}
              onBlur$={commitCurrent}
            />
          )}
          {m.parts.hexInput && (
            <input
              class={`${prefix}__field ${prefix}__field--hex ${prefix}__hex`}
              value={m.hex}
              spellcheck={false}
              aria-label="Hex colour"
              onInput$={(_, el) => editColour(el.value)}
              // Typing passes through half-entered colours, so the commit is
              // leaving the field rather than each keystroke.
              onBlur$={commitCurrent}
            />
          )}
          {m.parts.name && <span class={`${prefix}__name`}>{m.name}</span>}
        </div>
      )}

      {m.parts.notice && m.clipped && <p class={`${prefix}__notice`}>{m.notice}</p>}
    </div>
  );
});

// packages/react/src/ColourPicker.tsx
/** An OKLCH colour picker: one slider per axis, each over a gamut cross-section. */
import {
  type Gamut,
  type LabelKey,
  type Oklch,
  type PickerLayout,
  type PickerParts,
  addRecent,
  chartPick,
  colourName,
  emitValue,
  pickerModel,
  recentValue,
  resolveCurrent,
  toOklch,
  withSingleChart,
} from "@oklch-picker/core";
import { useState } from "react";
import { GamutChart } from "./GamutChart.js";

export interface ColourPickerProps {
  /** `oklch(L C H)` or hex. */
  value: string | null | undefined;
  /** Called with a canonical, gamut-clamped `oklch(L C H)` string. */
  onChange: (colour: string) => void;
  presets?: string[];
  /** Recently used colours, most recent first. Omit to let the picker keep its
   * own list for the session; pass one to store them yourself, in a backend,
   * or shared between pickers. */
  recents?: string[];
  /** Called with the new list when a colour is committed, for the controlled
   * form above. Fires on commit, so on a pointer release, a preset, or a hex
   * entry. Not on every value a drag passes through. */
  onRecentsChange?: (recents: string[]) => void;
  /** How many recents to keep. Ignored when `recents` is controlled: the list
   * you pass is the list that renders. */
  maxRecents?: number;
  /** Visual arrangement. `chart` (the default) shows one large
   * lightness x chroma plot above all three sliders; `side-by-side` adds a right
   * rail for the readout and presets; `compact` drops the charts entirely and
   * inlines each label with its slider; `stacked` gives every axis its own
   * thin chart. */
  layout?: PickerLayout;
  /** Turn parts off, e.g. `{ charts: false, name: false }`. All on by default. */
  parts?: PickerParts;
  /** Override for translation. Keys are the three axes, `outOfGamut`, and
   * `outOf:<gamut id>` for a wider space's own notice. */
  labels?: Partial<Record<LabelKey, string>>;
  /** The output space: what the sliders reach, what is clamped, and what is
   * emitted. Defaults to sRGB. Import wider spaces from
   * `@oklch-picker/core/gamuts`; omitting this ships none of that code. */
  gamut?: Gamut;
  /** Spaces to outline on the charts without clamping to them. Defaults to
   * sRGB whenever `gamut` is wider, so the safe region stays visible. */
  references?: Gamut[];
  /** What the switcher offers, when `parts.gamutSwitch` is on. Defaults to the
   * output gamut plus its references. */
  gamutChoices?: Gamut[];
  /** Called when a switcher button is pressed. Omit to leave the buttons
   * inert. The app is driving `gamut` as a prop either way. */
  onGamutChange?: (gamut: Gamut) => void;
  /** Class prefix for every element, so styles can be overridden. */
  classPrefix?: string;
  className?: string;
}

export function ColourPicker(props: ColourPickerProps) {
  const prefix = props.classPrefix ?? "oklch-picker";

  // What was dialled, not what was emitted: dragging through an out-of-gamut
  // region must not destroy the other axes.
  const [draft, setDraft] = useState<Oklch | null>(null);

  // The output space decides what `resolveCurrent` compares against, so it is
  // read from the prop here rather than from the model it feeds.
  const current = resolveCurrent(draft, props.value, props.gamut);
  const model = pickerModel(current, {
    layout: props.layout,
    parts: props.parts,
    labels: props.labels,
    gamut: props.gamut,
    references: props.references,
    gamutChoices: props.gamutChoices,
  });
  const { labels, layout, hex, canonical, clipped } = model;
  const show = model.parts;
  // `chart` renders one plot for the whole picker rather than one per axis.
  const single = withSingleChart(layout) ? model.charts[0] : undefined;

  // Recents are uncontrolled until `recents` is passed, mirroring how `value`
  // works. The internal list is kept regardless so switching to controlled
  // mid-session does not lose it.
  const [ownRecents, setOwnRecents] = useState<string[]>([]);
  const recents = props.recents ?? ownRecents;

  // A drag calls `onChange` for every value it passes through, so recording
  // there would bury the list in near-identical colours from one gesture.
  // Only a commit lands here. That is a pointer release, a preset or a hex
  // entry.
  const commit = (colour: string) => {
    const next = addRecent(recents, colour, props.maxRecents);
    setOwnRecents(next);
    props.onRecentsChange?.(next);
  };
  // Null while the dialled colour is outside the gamut, so a drag released in
  // a hatched region records nothing rather than the clamped near-miss.
  const commitCurrent = () => {
    const colour = recentValue(current, model.gamut);
    if (colour) commit(colour);
  };

  const emit = (next: Oklch) => {
    setDraft(next);
    props.onChange(emitValue(next, model.gamut));
  };
  const pick = (colour: string) => {
    setDraft(null);
    props.onChange(colour);
    commit(colour);
  };
  // Handlers are bound to both onInput and onChange. React fires the latter,
  // Preact the former. Each pair shares one function.
  //
  // `toOklch` rather than a per-field parser: a field accepts any supported
  // format whichever one it shows, so pasting a hex into the oklch field works
  // instead of being a rule to learn.
  const editColour = (e: { target: EventTarget | null }) => {
    const parsed = toOklch((e.target as HTMLInputElement).value);
    if (parsed) emit(parsed);
  };

  // Fully opaque drops the key rather than storing `a: 1`, so a colour dragged
  // to opaque emits `oklch(L C H)` and not `oklch(L C H / 1)`. One shape for
  // "opaque", set in one place.
  const slideAlpha = (e: { target: EventTarget | null }) => {
    const a = Number((e.target as HTMLInputElement).value);
    const { a: _drop, ...rest } = current;
    emit(a >= 1 ? rest : { ...rest, a });
  };

  return (
    <div className={[prefix, `${prefix}--${layout}`, props.className].filter(Boolean).join(" ")}>
      {props.presets && props.presets.length > 0 && (
        <div className={`${prefix}__presets`}>
          {props.presets.map((p) => {
            const selected = p === canonical;
            return (
              <button
                key={p}
                type="button"
                className={`${prefix}__preset${selected ? ` ${prefix}__preset--selected` : ""}`}
                style={{ background: p }}
                onClick={() => pick(p)}
                aria-label={colourName(p)}
                aria-pressed={selected}
              />
            );
          })}
        </div>
      )}

      {show.recents && recents.length > 0 && (
        <div className={`${prefix}__recents`}>
          {recents.map((r) => (
            <button
              key={r}
              type="button"
              className={`${prefix}__recent${r === canonical ? ` ${prefix}__recent--selected` : ""}`}
              style={{ background: r }}
              onClick={() => pick(r)}
              aria-label={`Recent: ${colourName(r)}`}
              aria-pressed={r === canonical}
            />
          ))}
        </div>
      )}

      {single && (
        <GamutChart
          base={current}
          axis={single.axis}
          id={single.axis}
          x={single.x}
          y={single.y}
          references={model.references}
          gamut={model.gamut}
          scaleGamuts={model.scaleGamuts}
          onPick={(x, y) =>
            emit(chartPick(current, single.axis, x, y, model.gamut, model.scaleGamuts))
          }
          onPicked={commitCurrent}
          classPrefix={prefix}
        />
      )}

      <div className={`${prefix}__axes`}>
        {model.axes.map((a, i) => {
          const spans = model.spans[i] ?? [];
          // In the `chart` layout the one chart is hoisted above the axes.
          const chart = single ? undefined : model.charts[i];
          const slide = (e: { target: EventTarget | null }) =>
            emit({ ...current, [a.key]: Number((e.target as HTMLInputElement).value) });
          // A div, not a label. The slider has its own aria-label.
          return (
            <div key={a.key} className={`${prefix}__axis`}>
              <span className={`${prefix}__axis-head`}>
                <span className={`${prefix}__axis-label`} aria-hidden="true">
                  {layout === "compact" ? a.key.toUpperCase() : labels[a.key]}
                </span>
                <output className={`${prefix}__axis-value`}>
                  {a.key === "h" ? Math.round(a.value) : a.value.toFixed(2)}
                </output>
              </span>

              {/* Read-only here: a 34px strip gives a drag almost no vertical
                  travel, and it would set two axes at once right above the
                  slider that sets one precisely. Only `chart` is big enough. */}
              {chart && (
                <GamutChart
                  base={current}
                  axis={a.key}
                  id={a.key}
                  x={chart.x}
                  y={chart.y}
                  references={model.references}
                  gamut={model.gamut}
                  scaleGamuts={model.scaleGamuts}
                  classPrefix={prefix}
                />
              )}

              <span className={`${prefix}__track`}>
                <span
                  className={`${prefix}__track-fill`}
                  style={{ background: model.gradients[i] }}
                >
                  {spans.map((s) => (
                    <span
                      key={`${a.key}-${s.start}`}
                      className={`${prefix}__out-of-gamut`}
                      style={{ left: `${s.start * 100}%`, width: `${(s.end - s.start) * 100}%` }}
                    />
                  ))}
                </span>
                <input
                  type="range"
                  className={`${prefix}__slider`}
                  min={a.min}
                  max={a.max}
                  step={a.step}
                  value={a.value}
                  aria-label={labels[a.key]}
                  onInput={slide}
                  onChange={slide}
                  // The gesture ending is the commit, not each value it passed
                  // through. `blur` catches the keyboard: arrowing along a
                  // slider should record once the user moves on, not per step.
                  onPointerUp={commitCurrent}
                  onBlur={commitCurrent}
                />
              </span>
            </div>
          );
        })}

        {/* Alpha rides with the axes for layout but is not one of them. It has
            no gamut chart and no hatching, because transparency cannot put a
            colour outside what a screen can show. */}
        {model.withAlpha && (
          <div className={`${prefix}__axis ${prefix}__alpha`}>
            <span className={`${prefix}__axis-head`}>
              <span className={`${prefix}__axis-label`} aria-hidden="true">
                {layout === "compact" ? "A" : "Alpha"}
              </span>
              <output className={`${prefix}__axis-value`}>{model.alpha.value.toFixed(2)}</output>
            </span>

            <span className={`${prefix}__track`}>
              <span className={`${prefix}__track-fill`}>
                <span className={`${prefix}__alpha-check`} />
                <span
                  className={`${prefix}__alpha-ramp`}
                  style={{ background: model.alpha.track }}
                />
              </span>
              <input
                type="range"
                className={`${prefix}__slider`}
                min={model.alpha.min}
                max={model.alpha.max}
                step={model.alpha.step}
                value={model.alpha.value}
                aria-label="Alpha"
                onInput={slideAlpha}
                onChange={slideAlpha}
                onPointerUp={commitCurrent}
                onBlur={commitCurrent}
              />
            </span>
          </div>
        )}
      </div>

      {model.withGamutSwitch && (
        /* biome-ignore lint/a11y/useSemanticElements: a <fieldset> is for form
           controls and brings a legend and its own box; this is a toolbar of
           buttons, which is what role="group" describes. */
        <div className={`${prefix}__gamut-switch`} role="group" aria-label="Output gamut">
          {model.gamutChoices.map((g) => {
            const selected = g.id === model.gamut.id;
            return (
              <button
                key={g.id}
                type="button"
                className={`${prefix}__gamut-choice`}
                aria-pressed={selected}
                aria-label={`Output in ${g.label}`}
                onClick={() => props.onGamutChange?.(g)}
              >
                {g.label}
              </button>
            );
          })}
        </div>
      )}

      {model.withFooter && (
        <div className={`${prefix}__footer`}>
          {show.preview && (
            <span
              className={`${prefix}__preview`}
              style={{ background: hex, color: model.light ? "#000" : "#fff" }}
              title={clipped ? model.notice : canonical}
            />
          )}
          {/* Every field accepts any supported format, whichever it displays.
              Pasting a hex into the oklch field works, because refusing it
              would be a rule the reader has to learn for no benefit. */}
          {show.oklchInput && (
            <input
              className={`${prefix}__field ${prefix}__field--oklch`}
              value={model.oklch}
              spellCheck={false}
              aria-label="OKLCH colour"
              onInput={editColour}
              onChange={editColour}
              onBlur={commitCurrent}
            />
          )}
          {show.rgbInput && (
            <input
              className={`${prefix}__field ${prefix}__field--rgb`}
              value={model.rgb}
              spellCheck={false}
              aria-label="RGB colour"
              onInput={editColour}
              onChange={editColour}
              onBlur={commitCurrent}
            />
          )}
          {show.hexInput && (
            <input
              className={`${prefix}__field ${prefix}__field--hex ${prefix}__hex`}
              value={hex}
              spellCheck={false}
              aria-label="Hex colour"
              onInput={editColour}
              onChange={editColour}
              // Typing passes through half-entered colours, so the commit is
              // leaving the field rather than each keystroke.
              onBlur={commitCurrent}
            />
          )}
          {show.name && <span className={`${prefix}__name`}>{model.name}</span>}
        </div>
      )}

      {show.notice && clipped && <p className={`${prefix}__notice`}>{model.notice}</p>}
    </div>
  );
}
